dist: bionic
sudo: required
language: java
jobs:
  fast_finish: true
  include:
  - build: ppc64le
    os: linux
    arch: ppc64le
    jdk: openjdk17
    script: mvn install -Dmaven.javadoc.skip=true --add-opens java.base/java.lang=ALL-UNNAMED
    addons:
      apt:
        packages:
        - maven
        - curl
  - build: s390x
    os: linux
    arch: s390x
    jdk: openjdk17
    # because of flakiness of tests on s390x, adding automatic retries on failure
    script: mvn install -Dmaven.javadoc.skip=true -Dfailsafe.rerunFailingTestsCount=10 --add-opens java.base/java.lang=ALL-UNNAMED
    addons:
      apt:
        packages:
        - maven
        - curl
services:
- docker
before_install:
- sudo rm /usr/bin/mvn
- wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz && tar -xvf apache-maven-3.9.9-bin.tar.gz
- sudo mv ./apache-maven-3.9.9/bin/mvn /usr/local/bin 
- mvn -version
- curl -s https://rubygems.org/downloads/asciidoctor-2.0.17.gem -o asciidoctor-2.0.17.gem
- gem install --local asciidoctor
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - BRANCH=${TRAVIS_BRANCH:-main}
  - TAG=${TRAVIS_TAG:-latest}
  - DOCKER_REGISTRY=quay.io
  - MVN_ARGS="-B"
  - TESTCONTAINERS_RYUK_DISABLED=TRUE
  - TESTCONTAINERS_CHECKS_DISABLE=TRUE
